// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServerMonitor.Infrastructure.Data;

#nullable disable

namespace ServerMonitor.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260902175728_AddTimestampIndexes")]
    partial class AddTimestampIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServerMonitor.Domain.Entities.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Threshold")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("ServerMonitor.Domain.Entities.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AlertsEnabled")
                        .HasColumnType("boolean");

                    b.Property<double>("CpuThreshold")
                        .HasColumnType("double precision");

                    b.Property<double>("DiskThreshold")
                        .HasColumnType("double precision");

                    b.Property<double>("MemoryThreshold")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlertsEnabled = true,
                            CpuThreshold = 90.0,
                            DiskThreshold = 90.0,
                            MemoryThreshold = 90.0
                        });
                });

            modelBuilder.Entity("ServerMonitor.Domain.Entities.MetricSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CpuUsagePercent")
                        .HasColumnType("double precision");

                    b.Property<double>("DiskTotalGb")
                        .HasColumnType("double precision");

                    b.Property<double>("DiskUsedGb")
                        .HasColumnType("double precision");

                    b.Property<double>("MemoryTotalMb")
                        .HasColumnType("double precision");

                    b.Property<double>("MemoryUsedMb")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("UptimeSeconds")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("MetricSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
